---
name: Latest blog post workflow
on:
  schedule:              # Run workflow automatically
    - cron: '4 4 4 ? * *'  # at 04:04:04 ever day
  workflow_dispatch:     # Run manually via GitHub Actions Workflow page

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get RSS Feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://practical.li/blog/feed.xml"
          max_post_count: 7
          
